### PR TITLE
updated to include support for linux. This commit fixes #1 

### LINKED ISSUE #1: Linux Build
Hello, I'm just asking without even trying.

But about the linux build, do you think it's just a matter of configurations or something more?

### PR DESCRIPTION
**Pull request by eperret**
updated to include support for linux. This commit fixes #1 The binary includes version 8 of nodejs and was tested on Ubuntu 14

### CODE REVIEW

**Comment by douglasmiranda** [comment]
I've tried to build here, and:

```
#@echo "Gathering 'svgo' sources"
#@git clone https://github.com/svg/svgo
#@rm -rf ./node_modules/svgo
Patching 'svgo' sources
cp: cannot stat './src/plugins/convertPathData.js': No such file or directory
Makefile:6: recipe for target 'prep-git' failed
make: *** [prep-git] Error 1
```

And on this specific step, if I look inside the _src/_ dir, it doesn't have the _./src/plugins/convertPathData.js_ file.

```
root@94add5b99192:/svgop# ls src/
RELEASE.md  domstubs.js  lib  listplugins.sh  pluginsList.js  pluginsMap.js  svgop.js
```

**Comment by douglasmiranda** [comment]
Maybe it should be: `cp ./svgo/plugins/convertPathData.js ./plugins/`?

**Comment by eperret** [comment]
Which directory were you executing the build from?  When I ran it I did not encounter any issue.

**Comment by douglasmiranda** [comment]
I've cloned your svgop repo, entered and ran `make`

**Comment by eperret** [comment]
Which version of Linux did you try it on?  I tried it on Ubuntu 16.

**Comment by douglasmiranda** [comment]
Debian Jessie

I don't know it doesn't seem to be an OS issue. I edited this line:

https://github.com/eperret/svgop/blob/master/Makefile#L18

with this code `cp ./svgo/plugins/convertPathData.js ./plugins/` and it worked.

When I look inside this dir https://github.com/eperret/svgop/tree/master/src it doesn't have the _plugins/convertPathData.js_

Oh yes, and I'm talking about the `prep-git` task.

**Pull request merged**
